name: Code Checks and Testing

on: [push, pull_request]

jobs:
  code_check:
    name: run PHP_CodeSniffer
    runs-on: ubuntu-latest

    steps:
      # Checkout code
      - name: Checkout code
        uses: actions/checkout@v3
      # Set up PHP
      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3' # Ensure this matches your project's PHP version
          extensions: mbstring, intl, pdo, xml, ctype, json
          tools: composer
      # Install dependencies
      - name: Run PHP_CodeSniffer
        run:  |
          vendor/bin/phpcs --standard=ruleset.xml --extensions=php --tab-width=4 -sp src tests
